---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-app
  namespace: production
  labels:
    app: cloud-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cloud-app
  template:
    metadata:
      labels:
        app: cloud-app
    spec:
      serviceAccountName: cloud-app
      containers:
        - name: cloud-app
          image: gar-location-docker.pkg.dev/project-id/repository/image-name:image-version
          ports:
            - name: web
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            failureThreshold: 10
            httpGet:
              path: /
              port: cloud
            periodSeconds: 10
            initialDelaySeconds: 5
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi