---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-app
  namespace: monitoring
  labels:
    app: cloud-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cloud-app
  template:
    metadata:
      labels:
        app: cloud-app
    spec:
      serviceAccountName: cloud-app
      containers:
        - name: cloud-app
          image: gar-location-docker.pkg.dev/project-id/repository/image-name:image-version
          ports:
            - name: web
              containerPort: 8080
              protocol: TCP
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-configmap
                  key: host
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  key: postgres_user
                  name: postgres-credentials
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: postgres_password
          livenessProbe:
            failureThreshold: 10
            httpGet:
              path: /
              port: cloud
            periodSeconds: 10
            initialDelaySeconds: 5
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 256Mi