apiVersion: v1
kind: Service
metadata:
  name: cloud-app-service
  namespace: monitoring
  labels:
    app: cloud-app
spec:
  type: ClusterIP
  ports:
    - name: cloud
      port: 8081
      protocol: TCP
  selector:
    app: cloud-app