---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cloud-app-service
  namespace: apps
spec:
  endpoints:
    - honorLabels: true
      port: cloud
  namespaceSelector:
    matchNames:
      - apps
  selector:
    matchLabels:
      app: cloud-app-service