---
apiVersion: v1
kind: Service
metadata:
  name: cloud-app
  namespace: production
  labels:
    app: cloud-app
spec:
  type: LoadBalancer
  ports:
    - name: web
      port: 8080
      protocol: TCP
  selector:
    app: cloud-app