---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cloud-app
  namespace: apps
  labels:
    team: devops-by-example
spec:
  endpoints:
    - honorLabels: true
      port: web
      path: /actuator/prometheus
  namespaceSelector:
    matchNames:
      - apps
  selector:
    matchLabels:
      app: cloud-app