---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cloud-app
  namespace: production
  labels:
    team: devops-by-example
spec:
  endpoints:
    - honorLabels: true
      port: web
      path: /actuator/prometheus
  namespaceSelector:
    matchNames:
      - production
  selector:
    matchLabels:
      app: cloud-app