---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cloud-app-service
  namespace: default
spec:
  endpoints:
    - honorLabels: true
      port: cloud
  selector:
    matchLabels:
      app: cloud-app-service