global:
  scrape_interval: 15s

scrape_configs:
  - job_name: cloud-app
    metrics_path: '/actuator/prometheus'
    kubernetes_sd_configs:
      - role: endpoints
    relabel_configs:
      - source_labels: [__meta_kubernetes_service_label_app]
        action: keep
        regex: cloud-app
      - source_labels: [__meta_kubernetes_namespace]
        action: replace
        target_label: namespace
      - action: labelmap
        regex: __meta_kubernetes_service_label_(.+)
