apiVersion: v1
kind: Service
metadata:
  name: loki
  namespace: monitoring
  labels:
    app: loki
spec:
  type: LoadBalancer
  ports:
    - name: loki
      port: 3100
      protocol: TCP
  selector:
    app: loki