apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cloud-app-monitoring
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app:
  namespaceSelector:
    matchNames:
      - default
endpoints:
  - port: cloud-app-lb