apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: cloud-app-pod-monitor
  labels:
    team: devops
spec:
  selector:
    matchLabels:
      app: cloud-app-pod
  namespaceSelector:
    matchNames:
      - default
  podMetricsEndpoints:
    - port: cloud-app-lb