apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-app-deployment
  labels:
    app: cloud-app-pod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cloud-app-pod
  template:
    metadata:
      labels:
        app: cloud-app-pod
    spec:
      containers:
        - name: cloud-app-container
          image: gar-location-docker.pkg.dev/project-id/repository/image-name:latest
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            periodSeconds: 10
            initialDelaySeconds: 5
          resources:
            limits:
              cpu: 150m
              memory: 512Mi