apiVersion: v1
kind: Service
metadata:
  name: cloud-app-service
spec:
  selector:
    app: cloud-app-pod
  ports:
    - name: cloud-app-lb
      protocol: 'TCP'
      port: 8080
      targetPort: 8080
  type: LoadBalancer