name: Rollback cloud-app image to previous version

on:
  workflow_dispatch:
    inputs:
      imageTag:
        description: 'Image Tag for Rollback'
        required: true
        default: '0'

env:
  # GCP Auth settings
  CREDENTIALS_JSON: ${{ secrets.SERVICE_ACCOUNT_KEY }}
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  # GCP Artifact Repository settings
  REPOSITORY: cloud-app-repository
  GAR_LOCATION: europe-central2
  IMAGE: cloud-app-image
  # GCP Cluster Settings
  GKE_CLUSTER: cloud-app-cluster
  GKE_ZONE: europe-central2
  DEPLOYMENT_NAME: cloud-app-deployment

jobs:
  rollback-image:
    name: Rollback Image
    runs-on: ubuntu-latest
    steps:

      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Authenticate with gcloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ env.CREDENTIALS_JSON }}

      - name: Install the gcloud cli
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.PROJECT_ID }}
          skip_install: false
          version: latest
          install_components: 'gke-gcloud-auth-plugin'

      - name: Rollback deployment
        env:
          IMAGE_TAG: ${{ github.event.inputs.imageTag }}
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
          GAR_LOCATION: europe-central2
          REPOSITORY: cloud-app-repository
          IMAGE: cloud-app-image
        run: |
          gcloud container clusters get-credentials $GKE_CLUSTER --region $GKE_ZONE
        
          if [ "$IMAGE_TAG" = "0" ]; then
            kubectl rollout undo deployment/cloud-app -n monitoring
          else
            kubectl set image deployment/cloud-app cloud-app=$GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE:$IMAGE_TAG -n monitoring
          fi